### ISSUE TITLE
Link to UI Theme Designer disabled

### ISSUE THREAD

**Issue by ISHFlorian** [SAP/openui5-docs#52]
On the "Tools" Tab there used to be a Link to the UI Theme designer, which no longer seems to be there.

If this is not an issue but intentional would it be possible to let me know why?

**Comment by OlMue** [comment]
Hi and thanks for your contribution! The link used to point to a trial offering in the SAP Cloud Platform Neo environment. Since the trial environment has been retired for SCP Neo, the link was removed.

There's no direct link to the new trial offering for the UI Theme Designer for SAP BTP trial accounts. But to make the "Tools" tab more consistent, I have requested that the UI Theme Designer heading links to the [UI Theme Designer Community Page](https://community.sap.com/topics/ui-theme-designer). This page is a central point of entry for more information, also covering a way to try it out.

I will close this issue as soon as the link is available.

**Comment by OlMue** [comment]
Hi all, the link has been replaced in the meantime. Thanks again!
