### ISSUE TITLE
is reference to SAP Web IDE required?

### ISSUE THREAD

**Issue by arcanist123** [SAP/openui5-docs#58]
As far as I understand, Web IDE requires you to buy license for productive usage https://launchpad.support.sap.com/#/notes/0002554932 
Supposedly, this guide is written for developers who want to try free of charge ui library from SAP. It would be fair to at least mention the license costs of SAP Web IDE or better mention the free of charge alternative

**Comment by OlMue** [comment]
Hi @arcanist123,

Thanks for bringing this up. I can see your point. We have moved SAP Web IDE further down in the documentation hierarchy, so it's not mentioned as prominently anymore for quite a while now.

Under [Development Environment](https://openui5.hana.ondemand.com/topic/7bb04e05f9484e1b95b38a2e48ecef4f), we mention various options. The proprietary SAP tools like SAP Business Application Studio can be licensed of course, but you can also use them for free via a trial account. That's why we think they're relevant in the documentation. SAP Business Application Studio has been developed with UI5 development in mind, so it's definitely worth mentioning it.

In general, you can use any (free) JavaScript IDE.
